# Generated by Django 4.2.30 on 2026-09-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_company_jobposting_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='recruiter',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('JOBSEEKER', 'Job Seeker'), ('RECRUITER', 'Recruiter'), ('ADMIN', 'Admin')], default='JOBSEEKER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
