# Generated by Django 4.2.30 on 2026-09-27 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rename_recruiter_company_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='requirements',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(default='resumes/default.pdf', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
